// Copyright 2019-2021 Crytek GmbH / Crytek Group. All rights reserved.
// Autogenerated using GFxShaderMaker modified by Crytek (depot\SDK\3rdParty\Scaleform-4.6.34\Apps\Tools\GFxShaderMaker)

#pragma once
#include "Renderer/SFConfig.h"
#include "Kernel/SF_Types.h"
#include "Kernel/SF_Debug.h"

#if !defined(SF_RENDER_MAX_BATCHES)
	#define SF_RENDER_MAX_BATCHES 24
#endif

namespace Scaleform {
namespace Render {

struct Uniform
{
	enum Flags
	{
		Uniform_Builtin  = 1,
		Uniform_TexScale = 2,
	};

	enum UniformType
	{
		SU_alphatex,
		SU_boundColor,
		SU_cmatadd,
		SU_cmatmul,
		SU_compx,
		SU_compy,
		SU_cxadd,
		SU_cxmul,
		SU_cxmul1,
		SU_dsttex,
		SU_fsize,
		SU_gradtex,
		SU_mapScale,
		SU_maptex,
		SU_mipLevels,
		SU_mvp,
		SU_offset,
		SU_scale,
		SU_scolor,
		SU_scolor2,
		SU_srctex,
		SU_srctexscale,
		SU_tex,
		SU_texgen,
		SU_texscale,
		SU_textureDims,
		SU_vfuniforms,

		SU_Count,

		SU_VertexSize   = 960,
		SU_FragSize     = 40,
		SU_GeometrySize = 0,
		SU_HullSize     = 0,
		SU_DomainSize   = 0,
		SU_ComputeSize  = 0,

		SU_TotalSize    = SU_VertexSize + SU_FragSize + SU_GeometrySize + SU_HullSize + SU_DomainSize + SU_ComputeSize,
	};
	static const unsigned char UniformFlags[];
};

enum EShaderFeatures : uint64;

enum ShaderStages
{
	ShaderStage_Vertex,
	ShaderStage_Frag,
	ShaderStage_Count,
};

struct UniformVar
{
	int16 Location;
	int16 ShadowOffset;
	int16 Size;
	int16 ElementSize;
};

struct BatchVar
{
	int8  Offset;
	uint8 Size;
};

struct ShaderDesc
{
	enum ShaderVersion
	{
		ShaderVersion_Default
	};

	enum ShaderType
	{
		ST_None                                       = 0,

		ST_base_Batch                                 = 0x00000002,
		ST_base_Instanced                             = 0x00000004,
		ST_base_Position2d                            = 0x00000000,
		ST_base_Position3d                            = 0x00000008,
		ST_base_TexTG                                 = 0x00000000,
		ST_base_ATexTG                                = 0x00000200,
		ST_base_Vertex                                = 0x00000400,
		ST_base_TexTGTexTG                            = 0x00000800,
		ST_base_ATexTGATexTG                          = 0x00001000,
		ST_base_TexTGVertex                           = 0x00002000,
		ST_base_ATexTGVertex                          = 0x00004000,
		ST_base_Cxform                                = 0x00000010,
		ST_base_CxformAc                              = 0x00000100,
		ST_base_EAlpha                                = 0x00000020,
		ST_base_Mul                                   = 0x00000001,
		ST_base_Inv                                   = 0x00000040,
		ST_base_InverseGamma                          = 0x00000000,
		ST_base_TexDensity                            = 0x00000080,

		ST_start_base                                 = 0x00000001,
		ST_TexTG                                      = 0x00000001,
		ST_BatchTexTGCxform                           = 0x00000013,
		ST_TexTGEAlpha                                = 0x00000021,
		ST_BatchTexTGCxformAc                         = 0x00000103,
		ST_ATexTG                                     = 0x00000201,
		ST_Vertex                                     = 0x00000401,
		ST_VertexEAlpha                               = 0x00000421,
		ST_TexTGTexTG                                 = 0x00000801,
		ST_TexTGTexTGEAlpha                           = 0x00000821,
		ST_ATexTGATexTG                               = 0x00001001,
		ST_TexTGVertex                                = 0x00002001,
		ST_TexTGVertexEAlpha                          = 0x00002021,
		ST_ATexTGVertex                               = 0x00004001,
		ST_end_base                                   = 0x0000416D,

		ST_base_text_Batch                            = 0x00000002,
		ST_base_text_Instanced                        = 0x00000004,
		ST_base_text_Position2d                       = 0x00000000,
		ST_base_text_Position3d                       = 0x00000008,
		ST_base_text_Solid                            = 0x00000000,
		ST_base_text_Text                             = 0x00008000,
		ST_base_text_TexUV                            = 0x00010000,
		ST_base_text_ATexUV                           = 0x00040000,
		ST_base_text_Cxform                           = 0x00000010,
		ST_base_text_Mul                              = 0x00000001,
		ST_base_text_Inv                              = 0x00000040,
		ST_base_text_InverseGamma                     = 0x00000000,
		ST_base_text_TexDensity                       = 0x00000080,

		ST_start_base_text                            = 0x00080000,
		ST_Solid                                      = 0x00080000,
		ST_Text                                       = 0x00088000,
		ST_TexUV                                      = 0x00090000,
		ST_ATexUV                                     = 0x000C0000,
		ST_end_base_text                              = 0x000C008C,

		ST_mask_clear_DepthMaskClear                  = 0x00000000,

		ST_start_mask_clear                           = 0x00100000,
		ST_DepthMaskClear                             = 0x00100000,
		ST_end_mask_clear                             = 0x00100000,

		ST_base_video_Batch                           = 0x00000002,
		ST_base_video_Instanced                       = 0x00000004,
		ST_base_video_Position2d                      = 0x00000000,
		ST_base_video_Position3d                      = 0x00000008,
		ST_base_video_TexTGVertexOnly                 = 0x00000000,
		ST_base_video_YUV                             = 0x00000000,
		ST_base_video_YUVA                            = 0x00020000,
		ST_base_video_YUY2                            = 0x00040000,
		ST_base_video_Cxform                          = 0x00000010,
		ST_base_video_CxformAc                        = 0x00000100,
		ST_base_video_EAlpha                          = 0x00000020,
		ST_base_video_Mul                             = 0x00000001,
		ST_base_video_Inv                             = 0x00000040,
		ST_base_video_InverseGamma                    = 0x00000000,
		ST_base_video_TexDensity                      = 0x00000080,

		ST_start_base_video                           = 0x00180000,
		ST_YUV                                        = 0x00180000,
		ST_YUVA                                       = 0x001A0000,
		ST_YUY2                                       = 0x001C0000,
		ST_end_base_video                             = 0x001C012D,

		ST_cmatrix_Position2d                         = 0x00000000,
		ST_cmatrix_Batch                              = 0x00000000,
		ST_cmatrix_TexTG                              = 0x00000000,
		ST_cmatrix_CMatrixAc                          = 0x00000000,
		ST_cmatrix_CxformAc                           = 0x00000000,
		ST_cmatrix_EAlpha                             = 0x00000020,
		ST_cmatrix_Mul                                = 0x00000001,
		ST_cmatrix_InverseGamma                       = 0x00000000,

		ST_start_cmatrix                              = 0x00200000,
		ST_end_cmatrix                                = 0x00200021,

		ST_blurs_Position2d                           = 0x00000000,
		ST_blurs_Batch                                = 0x00000000,
		ST_blurs_TexTGVertexOnly                      = 0x00000000,
		ST_blurs_Box1                                 = 0x00000000,
		ST_blurs_Box2                                 = 0x00020000,
		ST_blurs_Blur                                 = 0x00000000,
		ST_blurs_CxformAc                             = 0x00000000,
		ST_blurs_Mul                                  = 0x00000001,
		ST_blurs_InverseGamma                         = 0x00000000,

		ST_start_blurs                                = 0x00280000,
		ST_Box1Blur                                   = 0x00280000,
		ST_Box1BlurMul                                = 0x00280001,
		ST_Box2Blur                                   = 0x002A0000,
		ST_end_blurs                                  = 0x002A0001,

		ST_shadows_Position2d                         = 0x00000000,
		ST_shadows_Batch                              = 0x00000000,
		ST_shadows_TexTGVertexOnly                    = 0x00000000,
		ST_shadows_Box2                               = 0x00000000,
		ST_shadows_ShadowBase                         = 0x00000000,
		ST_shadows_BevelBase                          = 0x00040000,
		ST_shadows_SColor                             = 0x00000000,
		ST_shadows_SColor2                            = 0x00010000,
		ST_shadows_SGrad                              = 0x00008000,
		ST_shadows_SGrad2                             = 0x00004000,
		ST_shadows_Base                               = 0x00000000,
		ST_shadows_HideBase                           = 0x00002000,
		ST_shadows_OuterBevel                         = 0x00000000,
		ST_shadows_InnerBevel                         = 0x00001000,
		ST_shadows_InnerShadow                        = 0x00000800,
		ST_shadows_FullBevel                          = 0x00000400,
		ST_shadows_CxformAc                           = 0x00000000,
		ST_shadows_Mul                                = 0x00000001,
		ST_shadows_InverseGamma                       = 0x00000000,

		ST_start_shadows                              = 0x00300000,
		ST_end_shadows                                = 0x00353001,

		ST_DisplacementMap_Position2d                 = 0x00000000,
		ST_DisplacementMap_Batch                      = 0x00000000,
		ST_DisplacementMap_TexTGVertexOnly            = 0x00000000,
		ST_DisplacementMap_DisplacementMap            = 0x00000000,
		ST_DisplacementMap_DMIgnore                   = 0x00000200,
		ST_DisplacementMap_DMColor                    = 0x00000100,
		ST_DisplacementMap_InverseGamma               = 0x00000000,

		ST_start_DisplacementMap                      = 0x00380000,
		ST_end_DisplacementMap                        = 0x00380200,

		ST_DrawableCopyPixels_Position2d              = 0x00000000,
		ST_DrawableCopyPixels_Batch                   = 0x00000000,
		ST_DrawableCopyPixels_DrawableCopyPixels      = 0x00000000,
		ST_DrawableCopyPixels_DrawableCopyPixelsAlpha = 0x00000080,
		ST_DrawableCopyPixels_InAlpha                 = 0x00000000,
		ST_DrawableCopyPixels_MergeAlpha              = 0x00000040,
		ST_DrawableCopyPixels_NoDestAlpha             = 0x00000020,
		ST_DrawableCopyPixels_CopyLerp                = 0x00000000,

		ST_start_DrawableCopyPixels                   = 0x00400000,
		ST_end_DrawableCopyPixels                     = 0x004000C0,

		ST_DrawableMerge_Position2d                   = 0x00000000,
		ST_DrawableMerge_Batch                        = 0x00000000,
		ST_DrawableMerge_TexTGTexTGVertexOnly         = 0x00000000,
		ST_DrawableMerge_DrawableMerge                = 0x00000000,

		ST_start_DrawableMerge                        = 0x00480000,
		ST_DrawableMerge                              = 0x00480000,
		ST_end_DrawableMerge                          = 0x00480000,

		ST_DrawableCompare_Position2d                 = 0x00000000,
		ST_DrawableCompare_Batch                      = 0x00000000,
		ST_DrawableCompare_DrawableCompare            = 0x00000000,

		ST_start_DrawableCompare                      = 0x00500000,
		ST_DrawableCompare                            = 0x00500000,
		ST_end_DrawableCompare                        = 0x00500000,

		ST_DrawablePaletteMap_Position2d              = 0x00000000,
		ST_DrawablePaletteMap_Batch                   = 0x00000000,
		ST_DrawablePaletteMap_DrawablePaletteMap      = 0x00000000,

		ST_start_DrawablePaletteMap                   = 0x00580000,
		ST_DrawablePaletteMap                         = 0x00580000,
		ST_end_DrawablePaletteMap                     = 0x00580000,

		ST_blends_Position2d                          = 0x00000000,
		ST_blends_Batch                               = 0x00000000,
		ST_blends_TexTGTexTGVertexOnly                = 0x00000000,
		ST_blends_BlendLighten                        = 0x00000000,
		ST_blends_BlendDarken                         = 0x00000010,
		ST_blends_BlendOverlay                        = 0x00000008,
		ST_blends_BlendHardlight                      = 0x00000004,
		ST_blends_BlendDifference                     = 0x00000002,
		ST_blends_BlendLayer                          = 0x00000001,

		ST_start_blends                               = 0x00600000,
		ST_BlendLighten                               = 0x00600000,
		ST_BlendLayer                                 = 0x00600001,
		ST_BlendDifference                            = 0x00600002,
		ST_BlendHardlight                             = 0x00600004,
		ST_BlendOverlay                               = 0x00600008,
		ST_BlendDarken                                = 0x00600010,
		ST_end_blends                                 = 0x00600010,

	};

	static void GetTechniqueAndShaderFeatures(ShaderType type, CCryNameTSCRC& technique, EShaderFeatures& permutation);
};

struct TechniqueDesc
{
	struct VertexAttrDesc
	{
		const char*     Name;
		unsigned        Attr;
		const char*     SemanticName;
		unsigned        SemanticIndex;
		unsigned        Format;
		EShaderFeatures ShaderFeatures;
	};

	enum { MaxVertexAttributes = 4 };

	inline static const TechniqueDesc* GetDesc(ShaderDesc::ShaderType shader, ShaderDesc::ShaderVersion ver) { return &GetDesc(shader); }
	static const TechniqueDesc&        GetDesc(ShaderDesc::ShaderType shader);

	UniformVar                         Uniforms[Uniform::SU_Count];
	BatchVar                           BatchUniforms[Uniform::SU_Count];
	uint16                             BatchSize;
	CCryNameTSCRC                      Technique;
	EShaderFeatures                    ShaderFeatures;
	VertexAttrDesc                     Attributes[MaxVertexAttributes];
	uint8                              NumAttribs;
};

} // ~Render namespace
} // ~Scaleform namespace
