# Copyright 2001-2021 Crytek GmbH / Crytek Group. All rights reserved.

def build(bld):

	bld.CryEngineModule(
		target     = 'CryGamePlatformNodes',
		vs_filter  = 'CryPlugins',
		file_list  = 'crygameplatformnodes.waf_files',

		pch        = 'StdAfx.cpp',
				
		includes   = [ 
			'../Interface'
		],

		# The exported includes are used by GameSDK only, CryEngine does not need them.
		module_provides = dict(
			includes = [
				bld.path.make_node('../Interface').abspath()
			]
		)
	)
		