option(FBX_SHARED "Use fbx shared library" ON)

find_package(Fbx REQUIRED)

if(WINDOWS)
	add_library(FbxSdk SHARED IMPORTED GLOBAL)
	set_target_properties(FbxSdk PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${FBX_INCLUDE_DIRS}")
	set_target_properties(FbxSdk PROPERTIES INTERFACE_COMPILE_DEFINITIONS FBXSDK_NEW_API=1)

	# if (MSVC_VERSION GREATER 1900) # Visual Studio > 2015
	# 	set(FBX_SUBFOLDER vs2015)
	# elseif (MSVC_VERSION EQUAL 1900) # Visual Studio 2015
	# 	set(FBX_SUBFOLDER vs2015)
	# elseif (MSVC_VERSION EQUAL 1800) # Visual Studio 2013
	# 	set(FBX_SUBFOLDER vs2013)
	# elseif (MSVC_VERSION EQUAL 1700) # Visual Studio 2012
	# 	set(FBX_SUBFOLDER vs2012)
	# endif()

	set_property(TARGET FbxSdk APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
	set_target_properties(FbxSdk PROPERTIES
		IMPORTED_LOCATION_DEBUG "${FBX_SHARED_LIB_DEBUG}"
		IMPORTED_IMPLIB_DEBUG "${FBX_LIB_DEBUG}")

	set_property(TARGET FbxSdk APPEND PROPERTY IMPORTED_CONFIGURATIONS PROFILE)
	set_target_properties(FbxSdk PROPERTIES
		IMPORTED_LOCATION_PROFILE "${FBX_SHARED_LIB}"
		IMPORTED_IMPLIB_PROFILE "${FBX_LIB}")

	set_property(TARGET FbxSdk APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
	set_target_properties(FbxSdk PROPERTIES
		IMPORTED_LOCATION_RELEASE "${FBX_SHARED_LIB}"
		IMPORTED_IMPLIB_RELEASE "${FBX_LIB}")

	target_link_libraries(FbxSdk INTERFACE fbx::sdk)
endif()
